// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ealtyxadztsfepcfcjji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbHR5eGFkenRzZmVwY2ZjamppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODQ2NzUsImV4cCI6MjA3MzY2MDY3NX0.htng2CQ6ivyHl5QEs3YepnfZ3anxe4Qmu3Dtq9Ky6Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});